\echo Use "CREATE EXTENSION probackup_ctl" to load this file. \quit

CREATE SCHEMA IF NOT EXISTS probackup;

-- stores all the catalog info
CREATE TABLE probackup.catalogs (
	   id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	   backup_path TEXT UNIQUE,
	   storage TEXT,
	   storage_name TEXT,
	   probackup_version INT,
	   probackup_bin TEXT
);

-- config for S3 catalogs
CREATE TABLE probackup.s3_config (
	   name TEXT,
	   s3_hostname TEXT,
	   s3_port TEXT,
	   s3_access_key TEXT,
	   s3_secret_key TEXT,
	   s3_region TEXT,
	   s3_bucket TEXT,
	   s3_https BOOLEAN
);

-- config for SFTP catalogs
CREATE TABLE probackup.sftp_config (
	   name TEXT,
	   sftp_hostname TEXT,
	   sftp_port TEXT,
	   sftp_user TEXT
);

-- register a catalog
CREATE FUNCTION probackup.register_catalog (backup_path TEXT,
	   storage TEXT DEFAULT 'FS',
	   storage_name TEXT DEFAULT '',
	   probackup_bin TEXT DEFAULT NULL
)
RETURNS text AS 'MODULE_PATHNAME', 'probackup_register_catalog'
LANGUAGE C VOLATILE;

-- show backups
CREATE FUNCTION probackup.show (
	   catalog_id BIGINT DEFAULT 0,
	   pg_instance TEXT DEFAULT ''
)
RETURNS TABLE (
-- this also "blessed" in the C code. look for BlessTupleDesc
		catalog_id BIGINT,
		pg_instance TEXT,
		backup_id TEXT,
		end_time TIMESTAMPTZ,
		backup_mode text,
		wal_mode text,
		current_tli bigint,
		duration interval,
		data_size bigint,
		wal_size bigint,
		compress_alg text,
		compress_ratio bigint,
		start_lsn pg_lsn,
		stop_lsn pg_lsn,
		status text
)
AS 'MODULE_PATHNAME', 'probackup_show'
LANGUAGE C STRICT;

-- create backup
CREATE FUNCTION probackup.backup (catalog_id BIGINT,
	   pg_instance TEXT,
	   backup_mode TEXT DEFAULT '',
	   wal_mode TEXT DEFAULT '',
	   backup_id TEXT DEFAULT '',
	   parent_backup_id TEXT DEFAULT ''
)
RETURNS text AS 'MODULE_PATHNAME', 'probackup_backup'
LANGUAGE C STRICT;

-- delete backup
CREATE FUNCTION probackup.delete (catalog_id BIGINT,
	   pg_instance TEXT,
	   backup_id TEXT
)
RETURNS TEXT
AS 'MODULE_PATHNAME', 'probackup_delete'
LANGUAGE C STRICT;

-- Read pg_probackup3 backup log (not available form probackup 2)
CREATE FUNCTION probackup.log (catalog_id BIGINT, pg_instance TEXT, backup_id TEXT)
RETURNS TEXT
AS 'MODULE_PATHNAME', 'probackup_log'
LANGUAGE C STRICT;


-- Mark key tables as pg_dump'able
SELECT pg_catalog.pg_extension_config_dump('probackup.catalogs', '');
SELECT pg_catalog.pg_extension_config_dump('probackup.s3_config', '');
SELECT pg_catalog.pg_extension_config_dump('probackup.sftp_config', '');
